export const users = [
    {
      id: 1,
      name: "Aurlie Kimmel",
      role: "User",
      team: "Development",
      status: "active",
      age: "22",
      avatar: "image/image1.jpg",
      email: "akimmel5@globo.com",
      storage: "low",
    },
    {
      id: 2,
      name: "Erl Srutton",
      role: "Admin",
      team: "Sales",
      status: "blocked",
      age: "24",
      avatar: "image/image2.jpg",
      email: "kristen.cooper@example.com",
      storage: "high",
    },
    {
      id: 3,
      name: "Hillery Ovenell",
      role: "Staff",
      team: "Development",
      status: "blocked",
      age: "25",
      avatar: "image/image3.jpg",
      email: "esrutton7@geocities.jp",
      storage: "medium",
    },
    {
      id: 4,
      name: "Jeannette Daintith",
      role: "Staff",
      team: "Management",
      status: "blocked",
      age: "29",
      avatar: "image/image4.jpg",
      email: "jdaintitha@blogger.com",
      storage: "high",
    },
    {
      id: 5,
      name: "Luce Meddings",
      role: "Staff",
      team: "Marketing",
      status: "active",
      age: "28",
      avatar: "image/image5.jpg",
      email: "lmeddings8@usa.gov",
      storage: "medium",
    },
    {
      id: 6,
      name: "Mariann Pepperrall",
      role: "Admin",
      team: "Management",
      age: "29",
      avatar: "image/image6.jpg",
      email: "mpepperrall6@tripadvisor.com",
      status: "active",
      storage: "low",
    },
    {
      id: 7,
      name: " Osbourne Wiskar",
      role: "Staff",
      team: "Design",
      status: "active",
      age: "27",
      avatar: "image/image7.jpg",
      email: "owiskar9@mlb.com",
      storage: "medium",
    },
    {
      id: 8,
      name: " Payton Espinola",
      role: "Staff",
      team: "HR",
      status: "blocked",
      age: "31",
      avatar: "image/image8.jpg",
      email: "pespinolab@hhs.gov",
      storage: "high",
    },
    {
      id: 9,
      name: "Roarke Woolford",
      role: "User",
      team: "Finance",
      status: "active",
      age: "33",
      avatar: "image/image9.jpg",
      email: "rwoolford1@nba.com",
      storage: "low",
    },
    {
      id: 10,
      name: "Steven Preuvost",
      role: "Staff",
      team: "Operations",
      status: "blocked",
      age: "35",
      avatar: "image/image10.jpg",
      email: "spreuvost4@webnode.com",
      storage: "medium",
    },
    {
      id: 11,
      name: "Wainwright Taffe",
      role: "Staff",
      team: "Development",
      status: "blocked",
      age: "22",
      avatar: "image/image11.jpg",
      email: "wtaffe3@addthis.com",
      storage: "high",
    },
    {
      id: 12,
      name: "Woody Guerra",
      role: "Staff",
      team: "Product",
      status: "blocked",
      age: "28",
      avatar: "image/image12.jpg",
      email: "wguerra2@freewebs.com",
      storage: "low",
    },
  ];
  